config/routes.rb
Rails.application.routes.draw do
  mount Mercury::Engine => '/'
  
  root 'pages#index'

  resources :pages do
    member { post :mercury_update }
    collection do
      get 'search'
    end
  end

  devise_for :users
  scope "/admin" do
    resources :users
    get 'pages', to: 'pages#manage', as: 'manage_pages'
  end

  devise_for :admins, :skip => [:registrations]

  get 'contact', to: 'contact#new'
  resource :contact, only: [:create], controller: :contact

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %><br>
    <%= f.text_field :author, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="action">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<div id="custom-form-container">
	<h1>Editing Page</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @page %> |
	<%= link_to 'Back', pages_path %>
</div>

app/views/pages/index.html.erb
<main>
  <div class="cd-fixed-bg cd-bg-1" data-stellar-background-ratio="0.3">
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <%= image_tag "me.jpg", :height => "400", :alt => "Justin Vrooman", :class => "img-circle face", :style => "position: relative;border: 10px solid #F8F8F8;margin-bottom: 32px;" %>
      <h1><span style="background: rgb(33, 33, 33); background: rgba(33, 33, 33, 0.7); border: 1px solid #060606; border-radius: 5px;">&nbsp;Justin Vrooman&nbsp;</span></h1>
      <h2><span style="background: rgb(33, 33, 33); background: rgba(33, 33, 33, 0.7); border: 1px solid #060606; border-radius: 5px;">&nbsp;Systems Administrator&nbsp;</span></h2>
    </div>
  </div> 

  <div class="cd-scrolling-bg cd-color-1">
    <a name="about"></a>
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <div class="box" style="display: inline-block; width: 70%; left: auto; right: auto;">
        <h2>About Me</h2>
        <div class="text">
          <p style="font-weight: bold;">
            My name is Justin Ray Vrooman. Born on January 5th of 1988 to my wonderful parents Ricky Ray and Candy Lynn in the City of Lansing, Michigan. I am the middle child with 2 beautiful sisters: Nicole (older) and Rachel (younger). I grew up on the west side of Lansing in the City of Grand Ledge. Kindergarten through the 12th grade were spent in the halls of the Grand Ledge Public School system and in the Spring of 2006 I graduated, an honors student, from Grand Ledge High School. Immediately following high school I entered Michigan State University where I would learn, work, find a career and grow into the adult I am today. In the Fall of 2014 I graduated from Michigan State University as a Bachelor of Science in Computer Science. Currently, I work at Michigan State University as a Systems Administrator for the Division of Engineering Computing Services in the College of Engineering. My role as a Systems Administrator is primarily the installation, configuration and maintenance of the hardware and software systems used to facilitate the function and growth of the College of Engineering as well as several external units.
          </p>
          <p>
            As a young kid I was very much interested in the outdoors. I lived the simple life of biking, swimming and catching frogs at the creek down the street. From an early age I had a fascination with science and more specifically with space and space exploration. However, in the 5th grade my parents got my siblings and me our first computer. My fascination with computers had already been sparked using my grandparents' before we got one of our own but once my family had a computer and eventually the internet my fascination with them exploded. From the early days of AOL chat rooms and instant messaging and the very first MMORPGs such as The Realm Online and Ultima Online to physically upgrading the hardware in our computers. It all fascinated me. In middle school I would begin playing with Remote Access Trojans (RATs) and other "script kiddy" tools which taught me a great deal about computer security and lead to my earliest forays into computer programming.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="cd-fixed-bg cd-bg-2" data-stellar-background-ratio="0.3">
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <h2><span style="background: rgb(33, 33, 33); background: rgba(33, 33, 33, 0.7); border: 1px solid #060606; border-radius: 5px;">&nbsp;Systems & Software&nbsp;</span></h2>
    </div>
  </div> 

  <div class="cd-scrolling-bg cd-color-2">
    <a name="systems"></a>
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <div class="box" style="display: inline-block; width: 70%; left: auto; right: auto;">
        <p style="font-weight: bold;">
          Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        </p>
        <p>
          Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque.
        </p>
      </div>
    </div>
  </div>

  <div class="cd-fixed-bg cd-bg-3" data-stellar-background-ratio="0.3">
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <h2><span style="background: rgb(33, 33, 33); background: rgba(33, 33, 33, 0.7); border: 1px solid #060606; border-radius: 5px;">&nbsp;Networking & Security&nbsp;</span></h2>
    </div>
  </div> 

  <div class="cd-scrolling-bg cd-color-3">
    <a name="network"></a>
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <div class="box" style="display: inline-block; width: 70%; left: auto; right: auto;">
        <p style="font-weight: bold;">
          Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        </p>
        <p>
          Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque.
        </p>
      </div>
    </div>
  </div>

  <div class="cd-fixed-bg cd-bg-4" data-stellar-background-ratio="0.3">
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <h2><span style="background: rgb(33, 33, 33); background: rgba(33, 33, 33, 0.7); border: 1px solid #060606; border-radius: 5px;">&nbsp;Hardware&nbsp;</span></h2>
    </div>
  </div> 

  <div class="cd-scrolling-bg cd-color-4">
    <a name="hardware"></a>
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <div class="box" style="display: inline-block; width: 70%; left: auto; right: auto;">
        <p style="font-weight: bold;">
          Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        </p>
        <p>
          Mauris in erat justo. Nullam ac urna eu felis dapibus condimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Proin condimentum fermentum nunc. Etiam pharetra, erat sed fermentum feugiat, velit mauris egestas quam, ut aliquam massa nisl quis neque.
        </p>
      </div>
    </div>
  </div>

  <div class="cd-fixed-bg cd-bg-5" data-stellar-background-ratio="0.3">
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <h2><span style="background: rgb(33, 33, 33); background: rgba(33, 33, 33, 0.7); border: 1px solid #060606; border-radius: 5px;">&nbsp;Education&nbsp;</span></h2>
    </div>
  </div> 

  <div class="cd-scrolling-bg cd-color-5">
    <a name="education"></a>
    <div class="cd-container" style="display: table-cell; vertical-align: middle;">
      <div class="box" style="display: inline-block; width: 70%; left: auto; right: auto;">
        <h2>Bachelor of Science in Computer Science</h2>
        <h3 style="margin-bottom: 0px; font-weight: lighter;">College of Engineering</h3>
        <h3 style="margin-top: 0px; font-weight: normal;">Michigan State University</h3>
        <div class="text">
          <p style="margin-top: 20px;">
            Fall of 2006 marked the beginning of my career as a student at Michigan State University. My declared major at the time I entered the University was Mechanical Engineering. I stuck with this major for a couple of semesters taking classes that would teach me to use MATLAB® and UGS NX/Solidworks as well as teach me the basics of Material Science, Statics and Thermodynamics. By this time I had lost interest in the study of Mechanical Engineering and decided to change my major for the first time to Computer Engineering. As a Computer Engineering major I was introduced to Circuits and the Fundamentals of Digital Logic but most importantly I began my Computer Science career by learning the Python and C++ programming languages. My interest in programming would lead to my changing majors a second time to Computer Science and Engineering. In the Fall of 2014, after having taken many courses in the field of Computer Science, I graduated a Bachelor of Science in Computer Science.<br /><br />
          </p>
          <h4 style="margin-bottom: 0px;">Areas of Study:</h4><br />
          Discrete Structures<br />
          Computer Organization and Architecture<br />
          Algorithms and Data Structures<br />
          Object-Oriented Software Design<br />
          Operating Systems<br />
          Software Engineering<br />
          Computer Networks<br />
          Introduction to Artificial Intelligence<br />
          Translation of Programming Languages<br />
          Information Retrieval<br />
          Collaborative Design<br />
        </div>
      </div>
    </div>
  </div>

  <div class="ndx-footer">
    <center><p>Copyright &copy; 2015 by Justin Vrooman</p></center>
  </div>
</main> 

<div id="ndx-nav" class="btn-group btn-group-justified" role="group">
  <a href="#about" class="btn btn-primary btn-lg">About me</a>
  <a href="#systems" class="btn btn-primary btn-lg">Systems & Software</a>
  <a href="#network" class="btn btn-primary btn-lg">Networking & Security</a>
  <a href="#hardware" class="btn btn-primary btn-lg">Hardware</a>
  <a href="#education" class="btn btn-primary btn-lg">Education</a>
</div>

<div id="mobile-ndx-nav" class="btn-group dropup">
  <button type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown" aria-expanded="false" style="width: 100%;">Jump to <span class="caret"></span></button>
  <ul class="dropdown-menu dropdown-menu-custom" role="menu">
    <li><a href="#about">About me</a></li>
    <li><a href="#systems">Systems & Software</a></li>
    <li><a href="#network">Networking & Security</a></li>
    <li><a href="#hardware">Hardware</a></li>
    <li><a href="#education">Education</a></li>
  </ul>
</div>

<div id='to-top'><a href="#top"><i class="fa fa-arrow-up fa-5x"></i></a></div>

app/views/pages/manage.html.erb
<div id="custom-container">

  <div class="col-md-6">
    <h2>Manage pages</h2>
  </div>
  <div class="col-md-6">
    <%= link_to 'New page', new_page_path, class: "btn btn-primary pull-right" %>
  </div>

  <table class="table table-hover">
    <tr>
      <th>Page ID</th>
      <th>Title</th>
      <th>Author</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= page.id %></td>
          <td><%= page.title %></td>
          <td><%= page.author %></td>
          <td><%= page.created_at %></td>
          <td><%= page.updated_at %></td>
          <td><%= link_to 'Show', page, class: "btn btn-info pull-right" %></td>
          <td><%= link_to 'Edit', edit_page_path(page), class: "btn btn-warning pull-right" %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/pages/new.html.erb
<div id="custom-form-container">
	<h1>New Page</h1>

	<%= render 'form' %>

	<%= link_to 'Back', pages_path %>
</div>

app/views/pages/search.html.erb
<div id="custom-container">

  <div class="col-md-6">
    <h2>Search results</h2>
  </div>
  <div class="col-md-6">
    <%= link_to 'New page', new_page_path, class: "btn btn-primary pull-right" %>
  </div>
 
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Author</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
 
    <tbody>
      <% @pages.each do |page| %>
        <tr>
          <td><%= raw page.title %></td>
          <td><%= raw page.author %></td>
          <td><%= link_to 'Show', page, class: "btn btn-default pull-right" %></td>
          <td><%= link_to 'Edit', edit_page_path(page), class: "btn btn-default pull-right" %></td>
          <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default pull-right" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/pages/show.html.erb
<div id="custom-container">

<!--
  <p>
    <strong>Title:</strong>
    <%= raw @page.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= raw @page.author %>
  </p>
 -->

  <p>
    <!-- <strong>Content:</strong> -->
    <div id="page_content" data-mercury="full"><%= raw @page.content %></div>
  </p>

</div>

<% if admin_signed_in? %>
  <center><%= link_to "Edit page", "/editor" + request.path, data: { save_url: mercury_update_page_path(@page) }, class: "btn btn-default", id: "edit-link", :style => "margin-bottom: 50px;" %></center>
<% end %>