config/routes.rb
Rails.application.routes.draw do
  mount Mercury::Engine => '/'
  
  root 'pages#index'

  resources :pages do
    member { post :mercury_update }
    collection do
      get 'search'
    end
  end

  devise_for :users
  scope "/admin" do
    resources :users
    get 'pages', to: 'pages#manage', as: 'manage_pages'
  end

  devise_for :admins, :skip => [:registrations]

  get 'contact', to: 'contact#new'
  resource :contact, only: [:create], controller: :contact

end

app/views/layouts/_footer.html.erb
<center><p>Copyright &copy; 2015 by Justin Vrooman</p></center>

<script type="text/javascript"> jQuery(parent).trigger('initialize:frame'); </script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-60953612-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<% @links = Page.all %>

<div class="navmenu navmenu-inverse navmenu-fixed-left offcanvas">
  <%= link_to 'JustinVrooman.ninja', root_path, class: "navmenu-brand" %>
  <ul class="nav navmenu-nav">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
    <% if admin_signed_in? %>
      <li><%= link_to 'New page', new_page_path %></li>
      <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
    <% end %>
    <hr>
    <% @links.each do |link| %>
      <li><%= link_to link.title, link %></li>
    <% end %>
  </ul>
</div>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle left-toggle closed" id="left-nav-icon" data-toggle="offcanvas" data-target=".navmenu" data-canvas="body">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar top-bar"></span>
        <span class="icon-bar middle-bar"></span>
        <span class="icon-bar bottom-bar"></span>
      </button>
      <%= link_to 'JustinVrooman.ninja', root_path, class: "navbar-brand" %>
    </div><!-- /.navbar-header -->

    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(root_path) %>"><a href="/">Home<!-- <span class="sr-only">(current)</span> --></a></li>
        <li class="<%= 'active' if current_page?(contact_path) %>"><a href="/contact">Contact<!-- <span class="sr-only">(current)</span> --></a></li>
      </ul>

      <%= form_tag search_pages_path, method: :get, class: "navbar-form navbar-left" do %>
        <div class="input-group">
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <span class="input-group-btn">
            <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
          </span>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit account', edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% elsif admin_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ninja moves <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Manage pages', manage_pages_path %></li>
              <li><%= link_to 'Manage users', users_path %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="<%= 'active' if current_page?(new_user_registration_path) %>"><%= link_to 'Sign up', new_user_registration_path %></li>
          <li class="<%= 'active' if current_page?(new_user_session_path) %>"><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>

      </ul>
    </div>

  </div><!-- /.container-fluid -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JustinVrooman.ninja</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "jquery.stellar.min", 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "jquery.expander.min", 'data-turbolinks-track' => true %>
  <script type="text/javascript">
    $(function () {
         var converter = new Markdown.Converter();
         var editor = new Markdown.Editor(converter);
         editor.run();
    });
  </script>
  <script src='https://www.google.com/recaptcha/api.js'></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= favicon_link_tag 'j.ico' %>
</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-fixed-top alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

<% if !current_page?(root_path) %>
  <div class="wrapper">
<% end %>
    <%= yield %>
<% if !current_page?(root_path) %>
    <div class="push"></div>
  </div>
<% end %>

<% if !current_page?(root_path) %>
  <div class="footer">
    <%= render 'layouts/footer' %>
  </div>
<% end %>

</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'jquery-1.7', 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: 'POST', // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>